// import { day01A, day01B } from './src/processing/01.js';
// import { day02A, day02B } from './src/processing/02.js';
// import { day03A, day03B } from './src/processing/03.js';
// import { Day04 } from './src/processing/04.js';
// import { Day05 } from './src/processing/05.js';
// import { Day06 } from './src/processing/06.js';
import { Day07 } from './src/processing/07.js';

// day01A();
// day01B();
// day02A();
// day02B();
// day03A();
// day03B();
// const day = new Day04();
// const day = new Day05();
// const day = new Day06();
const day = new Day07();
day.A();
// day.B();